version: "3.8"

networks:
  mongo_net:
    driver: bridge
volumes:
  mongodb_server_data:

services:
    
  #credit-card-integration:
  #container_name: credit-card-integration
  # restart: always
  # depends_on:
  #   - mongodb_cci_fiap
  # build:
  #   context: .
  # ports:
  #   - "5000:5000"
  # environment:
  #   MONGODB_HOST: mongodb_cci_fiap

  mongodb_cci_fiap:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_server_data:/data/db
      #- ./mongodb_cci_fiap/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      #- $PWD/docker/run/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js